### PR TITLE
Fix blocking feature and make private some non-public components

### LINKED ISSUE #79: Make private some non-public components
Such as [Toggle](https://docs.rs/furiosa-device/0.1.3/furiosa_device/struct.Device.html#method.ctrl_ne_clock), there are some components that are exposed but not public. I think they should be visible to users or made private for release.

### PR DESCRIPTION
**Pull request by yw-furiosa**
resolve #79 #74

### CODE REVIEW

File: device-api/src/device.rs [hunk 1]
```diff
@@ -203,7 +208,8 @@ impl Device {
     }
 
     /// List performance counters for each device files.
-    pub fn performance_counters(&self) -> Vec<(&DeviceFile, PerformanceCounter)> {
+    #[allow(dead_code)]
+    fn performance_counters(&self) -> Vec<(&DeviceFile, PerformanceCounter)> {
```
Comment (libc-furiosa) [inline device-api/src/device.rs:212]: This code is used in PR 81. I think we can keep it public and remove the dead_code as well.

File: device-api/src/device.rs [hunk 2]
```diff
@@ -376,7 +383,8 @@ impl DeviceInfo {
         Ok(node)
     }
 
-    pub fn get_performance_counter(&self, file: &DeviceFile) -> DeviceResult<PerformanceCounter> {
+    #[allow(dead_code)]
+    fn get_performance_counter(&self, file: &DeviceFile) -> DeviceResult<PerformanceCounter> {
```
Comment (libc-furiosa) [inline device-api/src/device.rs:387]: This code is used in PR 81. I think we can keep it public and remove the dead_code as well.

File: device-api/src/hwmon.rs [hunk 3]
```diff
@@ -107,10 +106,36 @@ struct MetricEntry {
     metric_item: MetricItem,
 }
 
-impl TryFrom<DirEntry> for MetricEntry {
+impl TryFrom<std::fs::DirEntry> for MetricEntry {
     type Error = error::HwmonError;
 
-    fn try_from(value: DirEntry) -> Result<Self, Self::Error> {
+    fn try_from(value: std::fs::DirEntry) -> Result<Self, Self::Error> {
```
Comment (libc-furiosa) [inline device-api/src/hwmon.rs:112]: This is the same as the `try_from` implementation for `TryFrom<tokio::fs::DirEntry>`. Is it available to separate it into a function that takes a string and let each implementation call it?

**Review by libc-furiosa — COMMENTED** [review]
Looks good to me. I left some comments.
On the other hand, the implementation that provides the blocking function seems to be verbose. It would be nice to refactor this in the next milestone.

**Review by libc-furiosa — APPROVED** [review]
Looks good to me. 👍
