### PR TITLE
Fix reading real time value from mgmt files

### LINKED ISSUE #78: Real time values ​​not updating
For example, the `heartbeat` value in device.rs comes from `device_info` structure. The `heartbeat` value is updated every second, but the `device_info` structure is not updated once created, so the correct `heartbeat` value of the device cannot be obtained. I think it should be read file and return value when it requested such as `Fetcher` in hwmon.rs.

### PR DESCRIPTION
**Pull request by yw-furiosa**
Resolve #78 . Adds indication which files contain real-time values ​​and disables caching for those values.

### CODE REVIEW

**Comment by libc-furiosa** [comment]
FYI) I gave feedback to @yw-furiosa offline. I explained the background of the existing implementation and what I was trying to process. yw-furiosa will do further implementation.

File: device-api/src/device.rs [hunk 1]
```diff
@@ -291,61 +291,64 @@ pub struct DeviceInfo {
     device_index: u8,
     dev_root: PathBuf,
     sys_root: PathBuf,
-    meta: DeviceMetadata,
+    arch: Arch,
+    meta: Mutex<HashMap<&'static str, String>>,
```
Comment (libc-furiosa) [inline device-api/src/device.rs:295]: `meta` doesn't seem to update its value after creation in `new`, does it need to be a `Mutex`?

**Review by libc-furiosa — COMMENTED** [review]
Looks good to me. I left one comment.

File: device-api/src/device.rs (hunk 1 above)
Comment (yw-furiosa) [reply device-api/src/device.rs]: Fix at [b1e2ce5](https://github.com/furiosa-ai/device-api/pull/83/commits/b1e2ce55cbd06bae1c92a0604310a11664018b8a)

File: device-api/src/blocking.rs [hunk 2]
```diff
@@ -93,10 +90,14 @@ fn list_devfs<P: AsRef<Path>>(devfs: P) -> io::Result<Vec<DevFile>> {
...
 fn is_furiosa_device(idx: u8, sysfs: &str) -> bool {
-    std::fs::read_to_string(npu_mgmt::path(sysfs, PLATFORM_TYPE, idx))
-        .ok()
-        .filter(|c| npu_mgmt::is_furiosa_platform(c))
-        .is_some()
+    std::fs::read_to_string(npu_mgmt::path(
+        sysfs,
+        npu_mgmt::StaticMgmtFile::PlatformType.path(),
+        idx,
+    ))
```
Comment (libc-furiosa) [inline device-api/src/blocking.rs:97]: I have a minor opinion. Which do you think is better?

```
npu_mgmt::path(sysfs, npu_mgmt::StaticMgmtFile::PlatformType.path(), idx)
```
or
```
npu_mgmt::StaticMgmtFile::PlatformType.path(sysfs, idx)
```


I'm not sure if it's proper for the `fn path()` in `trait MgmtFile` to return a `&str` rather than a `PathBuf`.

**Review by libc-furiosa — COMMENTED** [review]
@yw-furiosa 
I left one other comment. Please check it.

File: device-api/src/blocking.rs (hunk 2 above)
Comment (yw-furiosa) [reply device-api/src/blocking.rs:97]: I agree with that `fn path()` returns `&str` is not proper. Then, how about rename `fn path()` to `fn filename()`? There are some usage of current `fn path()` such as [here](https://github.com/furiosa-ai/device-api/pull/83#pullrequestreview-1517636358). And I think `fn filename()` returns '&str' is proper like [std::Path](https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.file_name).

Comment (libc-furiosa) [reply device-api/src/blocking.rs:97]: I think `filename` is better.

Comment (yw-furiosa) [reply device-api/src/blocking.rs]: Reflect at [6f3bc5e](https://github.com/furiosa-ai/device-api/pull/83/commits/6f3bc5ece0628d32a1ba7d2ad12b330cd951c191)

**Review by libc-furiosa — APPROVED** [review]
👍
